{"name": "test_001_login_out_success", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute 'login_api'", "trace": "self = <testcase.test02_login_out.TestLogin_out object at 0x11079ce50>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    # 正向功能，仅必填参数\n    def test_001_login_out_success(self):\n        # 获取token数据\n>       token = get_token()\n\ntest02_login_out.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../utils/token.py:18: in get_token\n    token_l = TestLogin().test_001_login_success()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <testcase.test01_login.TestLogin object at 0x110e8d1d0>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    # 正向功能，仅必填参数\n    def test_001_login_success(self):\n        # 获取json文件中的第i+1条测试用例data数据\n        json_data = get_json_data(0)\n        # self.logger.info(\"case001的输入的登录信息为：\"+json_data)\n        # 调用登录接口完成登录，json_data为传入的请求体内容\n>       response = self.login_api.login(json_data)\nE       AttributeError: 'TestLogin' object has no attribute 'login_api'\n\ntest01_login.py:27: AttributeError"}, "start": 1710215814137, "stop": 1710215814138, "uuid": "f94fb9fa-9242-4bc7-ae97-bb5f2fc3cb14", "historyId": "62ff7514285c81611904ca4e438ee397", "testCaseId": "62ff7514285c81611904ca4e438ee397", "fullName": "testcase.test02_login_out.TestLogin_out#test_001_login_out_success", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test02_login_out"}, {"name": "subSuite", "value": "TestLogin_out"}, {"name": "host", "value": "hkdeMacBook-Pro"}, {"name": "thread", "value": "78177-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test02_login_out"}]}